### ISSUE TITLE
For a more complete dataset

### ISSUE THREAD

**Issue by Theo-Stats** [Dhananjay42/crackseg9k#2]
Thank you very much for your work, which is very useful for the crack detection task.     According to you provide the address of "https://doi.org/10.7910/DVN/EGIEBY" I got the dataset.  However, it has not yet been classified into the three classes mentioned in your paper and has not yet been included the DINO feature.     Could you provide the relevant datasets?     thank you very much!!!

**Comment by shreyask3107** [comment]
Hi @Theo-Stats, Thanks for notifying us.
We will make classifications available in the csv and DINO feature generation code with weights, and the outputs will be shared on our repo. 
We will try to get this done by the end of the weekend.

**Comment by Theo-Stats** [comment]
Hi @shreyask3107, I am glad to have your reply.

Have you finished updating the dataset? Can you send me the new link?

Also, I have two new questions that I hope you can answer for me.
1. I found that the DINO algorithm uses the multi-head attention, and each time there are five output images, but the DINO feature part of the input in your model is single channel, how did you convert it?
2. Do you use pretrained weights of resnet in your model?

**Comment by shreyask3107** [comment]
Hi @Theo-Stats ,

@Siddharth02003 is working on it and we will let you know once we are done. Hopefully within a day or two.

1. We use one of the five outputs (layer 3). We do not use all of the five outputs because they seem to be correlated and one of them shall do the required job more efficiently.

2. Yes, we do pretrain when resnet backbone is used.

**Comment by Theo-Stats** [comment]
Hi @shreyask3107 ,
I would like to know how you use pretrain weight of ResNet on ImageNet, because the input of your model is 4 channels, while the input of the original ResNet is 3 channels.
Thanks!

**Comment by shreyask3107** [comment]
@Theo-Stats 
You can refer to our code in DeepLab, we have essentially loaded all layers except the first layer in such case.

**Comment by Dhananjay42** [comment]
Hello @Theo-Stats, we have fixed the bugs in the dataset and have also added a folder called 'Heads' which contains the DINO feature maps for our dataset. Instructions on generating the DINO feature maps have also been added to the repository under the folder 'dino'. 

Regards and hoping this helps,
Dhananjay.
