### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by liu-tianxiang** [Dhananjay42/crackseg9k#3]
I tried to reproduce your code but got such an error：‘FileNotFoundError: [Errno 2] No such file or directory: 'datasets/crack/ImageSets\\train.txt'’
And I saw that there is no .txt file in your dataset and the training and test sets are not divided. Can you tell how the code should be tuned

**Comment by shreyask3107** [comment]
Hi @liu-tianxiang , 

I think we haven't added the train.txt/val.txt in our dataset. However, they can be generated very easily. It just contains the list of all crack image names. This can simply be generated by going to the crack train folder in our dataset and running the following:
`ls > train.txt`

Similarly for validation.
To make it easier for everyone, we shall include the .txt files soon into our dataset. Thanks for pointing it out.

**Comment by liu-tianxiang** [comment]
Because I haven't run the code successfully, I have two questions. The data set only has pictures and true values, but "split='train', split='val'"(datasets.__init__ line25) appears in the code, and the code will automatically divide the training and validation sets ?
Another point is that _image = os.path.join(self._image_dir, line )（crack_feat lin58）, so the .txt file is two separate .txt file save images and true values path , or the same .txt file, save the image path and true value on the same line value path?

>

**Comment by shreyask3107** [comment]
Hi could you please be more specific about the files whose lines you are referring to? There are two folders in the repo, hence it will make it easier for us to understand your query.

But trying to answer your query, the code for deeplab does not automatically divide the dataset into train and val. You can yourself decide the split.
