### ISSUE TITLE
There seems to be an error in the dataset

### ISSUE THREAD

**Issue by liu-tianxiang** [Dhananjay42/crackseg9k#4]
in imgs   Rissbilder_for_Florian_9S6A2911_1125_1393_2108_2755.jpg  has found, but this picture is not found in the masks.

**Comment by shreyask3107** [comment]
Thanks for pointing it out. We have fixed that and will be uploading the new version soon.

**Comment by LovingThresh** [comment]
Thank you very much for your work, but I found that in the dataset, there is a mismatch between the image and the mask, especially the **Rissbilder_for_Florian dataset**, which has a lot of errors.

**Comment by LovingThresh** [comment]
After testing, we found that there are 744 pairs that cannot be matched, all of which come from Rissbilder_for_Florian.

**Comment by Dhananjay42** [comment]
Hey, @LovingThresh thank you for accurately identifying the issue with the dataset - it made our job a whole lot easier! There were a few issues in the dataset which we have fixed, and we have also updated the 'train.txt' and the 'test.txt' files to reflect the test-train split of the dataset. We're in the process of uploading the new dataset, and it should be accessible by tonight. 

Hope this helps!

**Comment by LovingThresh** [comment]
Thank you！Good Job！



| |
刘烨
中南大学本科生
|
|
15200945180
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 02/23/2023 17:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Dhananjay42/crackseg9k] There seems to be an error in the dataset (Issue #4) |

Hey, @LovingThresh thank you for accurately identifying the issue with the dataset - it made our job a whole lot easier! There were a few issues in the dataset which we have fixed, and we have also updated the 'train.txt' and the 'test.txt' files to reflect the test-train split of the dataset. We're in the process of uploading the new dataset, and it should be accessible by tonight.

Hope this helps!
