### ISSUE TITLE
About the denoiser

### ISSUE THREAD

**Issue by Theo-Stats** [Dhananjay42/crackseg9k#5]
Hi, there is a denoiser mentioned in your paper, but I neither find the denoiser I your code nor find the details in your paper.  
The effect of your denoiser is very good. It can remove some relatively large particles. I would like to know how you tackle the noise.
Thank you!!!

![image](https://user-images.githubusercontent.com/87311580/195335929-ac6f81b7-5ec2-49b6-9887-8bb8fa840556.png)

**Comment by Dhananjay42** [comment]
Hey, 

So, we noticed that sometimes our predictions had small specks/marks - which were undesirable. To tackle these, we performed a simple Morphological Opening (that is, erosion followed by dilation). We'll update the code we used to do this soon. 

Looking into other denoisers could be explored in further work - that was just a placeholder in the pipeline diagram. 

Hope this answers your question!
