### ISSUE TITLE
train/val/test split for the dataset

### ISSUE THREAD

**Issue by skokec** [Dhananjay42/crackseg9k#6]
Hi, would it be possible to obtain the exact train/val/test split of the images that you used in the paper? I have not been able to find any files in the dataset that would correspond to this split. 

Best,
Domen

**Comment by Dhananjay42** [comment]
Hi, we have added 'train.txt' and a 'test.txt' files to the dataset, which contain the names of the files in the test-train split. The updated dataset should be accessible from tonight. 

Regards,
Dhananjay
